### ISSUE TITLE
Issue installing on windows

### ISSUE THREAD

**Issue by joshua1** [tonyskn/express-soap2json#3]
I have been having an error with installing express-soap2json on windows 8 machine with node-gyp already installed. but it keeps failing at the node-gyp rebuild command. Please what do i do.
Thanks in advance

**Comment by tonyskn** [comment]
I must confess that I never tried installing this on Windows.  Could you please paste the output of `npm install` for more info ?

**Comment by joshua1** [comment]
Hi tonyskyn, soap.js has been updated to use sax.js instead of expat, making it entirely javascript and faster, installing easily on both unix and windows systems alike without the node-gyp issue. can you update the version of soap.js that this depends on.
Thanks

**Comment by tonyskn** [comment]
Sure, I'll have a look into it.  Thanks for the tip.

**Comment by joshua1** [comment]
you are welcome
